# Generated by Django 3.2 on 2021-04-15 19:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(default=1, max_length=75, unique=True)),
                ('country', models.CharField(max_length=75)),
                ('city', models.CharField(max_length=75, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkingTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_record', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[(1, 'StartWorkingTime'), (2, 'EndWorkingTime')], max_length=75)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NewUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=75, unique=True)),
                ('password', models.CharField(max_length=75)),
                ('role', models.CharField(choices=[('BOSS', 'BOSS'), ('ACCOUNTING', 'ACCOUNTING'), ('ACCOUNTING', 'GENERAL')], max_length=75)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.branchlocation')),
            ],
            options={
                'verbose_name': 'User',
                'db_table': 'Employees',
            },
        ),
    ]
