# Generated by Django 3.2 on 2021-04-15 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_workingtime_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchlocation',
            name='branch_name',
            field=models.CharField(max_length=75, unique=True),
        ),
        migrations.AlterField(
            model_name='workingtime',
            name='action',
            field=models.CharField(choices=[('StartWorkingTime', 'StartWorkingTime'), ('StartWorkingTime', 'EndWorkingTime')], max_length=75),
        ),
    ]
