# Generated by Django 3.2 on 2021-04-15 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210415_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workingtime',
            name='action',
            field=models.CharField(choices=[('StartWorkingTime', 'StartWorkingTime'), ('StartWorkingTime', 'StartWorkingTime')], max_length=75),
        ),
    ]
