# Generated by Django 3.2 on 2021-04-15 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_workingtime_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workingtime',
            name='action',
            field=models.CharField(choices=[('StartWorkingTime', 'StartWorkingTime'), ('EndWorkingTime', 'EndWorkingTime')], max_length=75),
        ),
    ]
