# Generated by Django 3.2 on 2021-04-15 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_workingtime_action'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workingtime',
            options={'verbose_name': 'Working Times'},
        ),
    ]
