# Generated by Django 3.2 on 2021-04-15 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_workingtime_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workingtime',
            options={'verbose_name': 'Working Time'},
        ),
    ]
