# Generated by Django 3.2 on 2021-04-15 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_workingtime_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branchlocation',
            options={'verbose_name': 'Branch Location'},
        ),
    ]
