# Generated by Django 3.2 on 2021-04-15 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_branchlocation_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='role',
            field=models.CharField(choices=[('BOSS', 'BOSS'), ('ACCOUNTING', 'ACCOUNTING'), ('GENERAL', 'GENERAL')], max_length=75),
        ),
    ]
